### PR TITLE
Added google sheets api and usage

### LINKED ISSUE #20: Research Python Google Sheets API
Find a way to use Python to send data

### PR DESCRIPTION
**Pull request by Guvn0**
test it out and see if it works for anyone else, also lemme know if there is any features I should include. Im not completely sure what else we might need for it so this is just a start.

### CODE REVIEW

**Review by guilleeh — APPROVED** [review]
LGTM!

**Comment by Guvn0** [comment]
any recommendations, changes or ideas? There could be some problems with people inputting at the same time so i have to do some testing on that, there's some optimizations we could include to API calls so that it puts a few on a buffer in python before writing all of them to the sheets which could also speed up requests and responses unless we need to read data from sheets but I'm not sure how multiple requests are handled in python (one-by-one or approx. simultaneously)

**Comment by guilleeh** [comment]
Check out this library if you want to make asynchronous calls in flask. https://flask-aiohttp.readthedocs.io/en/latest/

For now, since we are in the beginning stages, we can focus on getting something out that works, and then refactor & improve it later.

**Comment by Guvn0** [comment]
sounds good, ill make a second branch testing that stuff and including switches between different options we can use and let you guys decide later what would work better with what we have and want.

**Comment by josueal1** [comment]
@Guvn0  The code seems good! I'll merge it, yet I might revisit it a new branch to refactor down the line

**Review by josueal1 — COMMENTED** [review]
Looks good! will refactor later!

**Review by josueal1 — APPROVED** [review]

**Pull request merged**
